version: '3.8'

services:
  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${DEV_VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_TOKEN=${DEV_VAULT_TOKEN}
      - VAULT_ADDR=${DEV_VAULT_ADDR}

  ansible:
    build:
      context: ./ansible
      network: host
    environment:
      - VAULT_TOKEN=${DEV_VAULT_TOKEN}
      - VAULT_ADDR=${DEV_VAULT_ADDR}
